services:
  simple-reminder:
    image: ghcr.io/4lrick/simple-reminder:main
    container_name: simple-reminder
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - reminder-data:/app/data
    restart: unless-stopped

volumes:
  reminder-data:
    name: reminder-data